---
- name: VMware visbility
  hosts: localhost
  tasks:
    - name: Set VCenter parameters
      ansible.builtin.include_vars: login_info.yml

    - name: Use info role
      ansible.builtin.import_role:
        name: cloud.vmware_ops.info
      vars:
        info_license: true
        info_storage: true
        info_appliance: true
        info_guest: true
        info_cluster: true
        info_hostname: "{{ vcenter_hostname }}"
        info_username: "{{ vcenter_username }}"
        info_password: "{{ vcenter_password }}"
        info_validate_certs: false

    - name: Print __guests info
      ansible.builtin.debug:
        msg: "{{ __guests }}"

    - name: Print __clusters_info info
      ansible.builtin.debug:
        msg: "{{ __clusters_info }}"

    - name: Print __license info
      ansible.builtin.debug:
        msg: "{{ __license }}"

    - name: Print __storage_policy info
      ansible.builtin.debug:
        msg: "{{ __storage_policy }}"

    - name: Print __clusters info
      ansible.builtin.debug:
        msg: "{{ __clusters }}"

    - name: Template report into HTML
      ansible.builtin.include_role:
        name: "../roles/template"

    - name: Load report to host on AWS S3
      ansible.builtin.include_role:
        name: "../roles/build_report_s3"
      vars:
        reports_aws_bucket_name: vmware-report